dist: trusty
language: php
php:
  - 7

addons:
  sauce_connect:
    username:
      secure: "XOkgPTA2f6KxInMO9XgMqxyOdhgeOqJXSVbykn6xhcDATUeV1PdfeJYL3u/bfRUOPU5y7y4gqCrSRi8JYcW7vqozLTSHdhJsjbaibZGy50zGpUyyuGFs068XMVryOkkKqL0e2sju5RbHrnb32fVbftt82XfqkBoUuxyZRTnbSJ7w/PSoYmcG2b1fV7Xc5d/pkyTChIdn9NEOrcpbHZZRRxcTJk+506VTc5cD4jDrcRplby8oC+Aybm0HoOvhsgbGitfak9xbvpz+pIeazOpqmNxE96eBIqWvR91K5y36FTLH24xYF0vi/9NaSbiJ341OYEFyXbL6iUyTY3J0GVKOor7PfRxqK52EYoi6k0LsXwTDZ9JyBktx9dqk3ALJosd/dQdGh4v1Adq9apSPs92qLvBfLKdSOdfebYczpWlTAfPLg3EXFfwTIJ2RLBXGeWyRqk0EYV2zK/7F4XoKP4lka7+KOGEs/LtbmgYf/WqFkpUnbtvI1vzK9hhtszjydeTHb8zggvScuQhCP4zdXhm/W3yIFmHzJmfv/VtQgBdnjEjRscZ3F4PiAsBRcCt+5uwRKbwSR+I3JE4AHveTDzV5+jxGlKIP+TsLOahWpUAo12OjcqG1spHP3toSflrBrdE1vyTRWuwYVZ61Os5v4E0amreocAjcOqpRLWJ/1OFaahI="
    access_key:
      secure: "aLnteksdhd7384aHoiRgLZxXTUAw2CIYXvrJf6OcHq3+9C8YP4TOGpr6sf60cHalr0oQOV6QXUpvrRNqsZve45MtCvz8pwZTlKhgpLWUbRCFkvXdNlAi4wXqh8ZKTbeGao7YGhfxjvuABRsz4AglrL0VCD+3jbt0IamgUi0neksrgoQUHCKILBpctE6zKU3vDrVzaJ1QMW2BQJ5KaDG2xbSQN1YwcNsjcX2OZorIhnf31qppV4Wk0FjP4hrIKZcUHOjJm3hUgL82OpUyDXKm/6upBuUoDn8Vzq9d3cNLXjtPpgDRremfDGoQSDzDlyumIrivxwD2OQrmwMsRw1tHTX7acf4qub5FhKIMLsLvhix3RS8gdpdqApqufO4aP5dBDHh3AC3BsOl9r7PFIKbrkByhkehahkP9f1eZ/2XwdngnIxEuxJgNcQHEnW+nSN7TAaLtEsczCC2RZe61O3ogM6QhOT+tJuWkJMOBAMXOOIXlrl/1V1h1gg+uiSSHFFApZ4inGxKAnSta3MorothgnQPCXPZN/hovvCIb1IWFhQDv+oG1Q2/u8E1VzP3qTvr6UkELyfQy7VocGgXvj7nHO4Vtaj9IvqVBpUom+J3oug/RMVDUz5xtzU4ryHAGj3stJ/NQjL93jk4cRc+FLzsQqDyC9WfKUcs8wH1mcFuDjs4="

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

#services:
#  - mysql
env:
  matrix:
    - TRAVIS_NODE_VERSION="6"
  global:
    # travis encrypt SENV="secretvaluesetenv"
    - secure: "cL+IfhkurhwiJPrWMUqRZb+x4mYh9EHCb1l1bXHbXuCw/TWLqKMi6/O5WfVYb6UaIhgnqK+4BnHWs2kZr+sLucIKZalUWZEU996AaBecu+Q6F13RUungalT2iKyyIF2r+my9APDa83LBGVObSyhMX5x/p+mPNkyeo3rUDNvtqp7/JDyzAE0ZitFEpQdAYrOkDmWjc23uckFy+axEmAd3liLbZvQD9A+NNjeTCW7EPiCskRaBTr+c5M+EP8S7pLGivCJfx9tn4g4MoFoPNeUuWDyh8avdaMXJTbdDQ7iU1KiqTBq0kasON8bjm8rkBcmO7pw0lVI34nFNb1UAK9tbnc/BN7HYFXsZ1K/5RG1FBzeH8RZMpm5BBtXT63288aX/2NU78wRLi5yNucK77S7pSLFYRC5y8Z+WCwMKbbkH4x1kB7MxwP7KaKfn59WDC79AYR1bO1dlNwkCO4HdQBPwx/TX0rPbu+SLR84etGI5J1gJj4epmwHcaOhCNsnriX84MQ1qaXnn89SBbgq9Lgxmtsetfi8Gm6JRLVAckWatHEyY6wWkI/ZQSW351Chj241o0VCRsLuUgB3NmdUJOUVKkmZlnVPtozAotlzRxs0ScSi+2lZni6OfNzXlIvKbpm8qqrlUFzhX8bPN+1Oel2RdIiglLAdD1tpgtzTfluFrA8E="

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

sudo: true # with ports higher then 1024 no need to use sudo

before_script: # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "echo $SENV;"
  - php -S localhost:1025 & disown
  - sleep 3
  - curl localhost:1025/fixtures/event.php -I
  - "cd protractor"
  - php -v
  - node -v
  - yarn

script:
  # i'm still in protractor directory, then:
  - node node_modules/protractor/bin/protractor conf.js
