dist: trusty
language: php
php:
  - 7

addons:
  sauce_connect:
    username:
      secure: "XOkgPTA2f6KxInMO9XgMqxyOdhgeOqJXSVbykn6xhcDATUeV1PdfeJYL3u/bfRUOPU5y7y4gqCrSRi8JYcW7vqozLTSHdhJsjbaibZGy50zGpUyyuGFs068XMVryOkkKqL0e2sju5RbHrnb32fVbftt82XfqkBoUuxyZRTnbSJ7w/PSoYmcG2b1fV7Xc5d/pkyTChIdn9NEOrcpbHZZRRxcTJk+506VTc5cD4jDrcRplby8oC+Aybm0HoOvhsgbGitfak9xbvpz+pIeazOpqmNxE96eBIqWvR91K5y36FTLH24xYF0vi/9NaSbiJ341OYEFyXbL6iUyTY3J0GVKOor7PfRxqK52EYoi6k0LsXwTDZ9JyBktx9dqk3ALJosd/dQdGh4v1Adq9apSPs92qLvBfLKdSOdfebYczpWlTAfPLg3EXFfwTIJ2RLBXGeWyRqk0EYV2zK/7F4XoKP4lka7+KOGEs/LtbmgYf/WqFkpUnbtvI1vzK9hhtszjydeTHb8zggvScuQhCP4zdXhm/W3yIFmHzJmfv/VtQgBdnjEjRscZ3F4PiAsBRcCt+5uwRKbwSR+I3JE4AHveTDzV5+jxGlKIP+TsLOahWpUAo12OjcqG1spHP3toSflrBrdE1vyTRWuwYVZ61Os5v4E0amreocAjcOqpRLWJ/1OFaahI="
    access_key:
      secure: "GjKWWVrwD/Ah1wyzBE0uGea2iTO4fWNQVe6g7hi0ARZp31t+6iCmePV3x/rHK/bDeQvBeP1MGXkCCb17nYqVl/TGHJKMc7e8LEb0DzXsl7BEqmlK/bg21N2n+BoGI1h5kFwR0sP4MGTMGMYyyIeLwgmGw67x0XcxY3BFaQzORAuAqzJlbvmFr9ZsTCAeNqQ0s1fE/kCSwbZYemM4ny42QWNHpC/LYg900iWetqztgk3rKWxVfURVgntCbbQNcSAvxUjp8Uv/XTchGEWSY3m62OGguPafVG4TbVTX39qkIuXuqiqvLg4xujuFqVLnlYeGmvIm1DkNjjpQ5JMwrviIn3Uv3h3h/ZmB9q5DfgdkA36imixjISfeYwng0lfC/XTEPtUgFVRuEj7zUnvRy5AOjHYaLsUCEl0Gj0OP8MvGKHCASMWou1YRvamFgNpZvabVQ/arigG5jr2ohjb8wQ0m5ZCQhDCIK8z+DAJtYFh4MuZTn9VKdw2JyMnia0PtcxBQpXUjjdiyVDCZtE4/0D9tKFL27ndEeilQFUGn5Umg97R6X2WHypB3ZDrtrXucPeybrwwc5e94ftL64f97mTe5ZVDtCVM5zqK3b3DDadt2d53LUh91XBALTi09syXTQmXQIxDufSgp/MK0L+J01W5nZ7mSEr2gh45yf4RcHI6aBfA="

# https://docs.travis-ci.com/user/firefox/
# because of error https://stackoverflow.com/a/40232825
#addons:
#  firefox: "50.0b6"


before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

#services:
#  - mysql
env:
  - TRAVIS_NODE_VERSION="6"
  global:
    secure: "YjiWnxbwyHgo0j6FNm+derD7tz02DeVqdNdcNdYAuBAXjDDpi07F/e8+GEOMTGqS0HXJ8v9VctYOyxmlqaffLX95Ifu8rY2dhNHv1Aeuq5WJuOkTuW4VzCjpphuLs0QgNVIXz/3vAH0UafnWYHjlRCS7cKQaKvpWAba2GzazEm/pkyh/lywtC2vfeEf6E2EH07yp43uLPrFsoP10Akf7O3pz4XujcXzmcVCFiTDYPqohujnXuSMTTHkQsSnFVf8wTrtyPeRvYB4oweaoZ6A7/G0lhbKrN8FheVxZc8ZW+S7FwGVCawcM62bwPgZkKcjkroaechADfz1+RHcjrJ0Z8lstRlzqpdxwdfJc8DNqPbKIBKbYYC5R6iEkNaX2Nzcy27OMKw2K084FQaYPrknVr8pXfysstsengyvXNNwcv9csP45xvL1xrw+mCCLLE/5EQCGHcG2u7B6zy4IctGgbGf/6ZMRWqOS7OdJvLKf1RcLynkYyDWirGEeaPuF2u/W7nwr3w8m1wtlhDbxa72veXF/4gLzBgSRd/HzLfsIOj+DV0lfDXW1fWGeEwxkNIuTsEpGJ39eqdcUpRJDMmtY6uwmlRDR9Gzu/0FmCB2LektLpOxfpnnJBQx4w8DziMSbtJ5MI0mDdMecJQ6yl7tnQKTFO6OyR+FT2+V9IkT8EPGk="

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

sudo: true # with ports higher then 1024 no need to use sudo

#install:
#  - npm install -g yarn # no need to install yarn https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Travis-CI-supports-yarn
#  - yarn # no need to even execute yarn if there is yarn.lock file

before_script: # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
  - "echo 'cd protractor && yarn'"
  - echo $SENV;
  - php -S localhost:1025 & disown
  - sleep 5
  - curl localhost:1025/fixtures/event.php -I
  - "cd protractor"
#  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
#  - sudo apt-get install -y nodejs
  - php -v
  - node -v
#  - sudo npm cache clean -f
#  - sudo npm install -g n
#  - sudo n 6.5.0
#  - node -v
  - yarn
  - php -v
  - node -v
  - node node_modules/protractor/bin/webdriver-manager update
  - node node_modules/protractor/bin/webdriver-manager start & disown
  - sleep 5
  - curl localhost:4444 -I
  # alternatively
  #- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  #- sleep 3 # give xvfb some time to start
#  - npm run server & disown #https://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
#  - npm run parser & disown
#  - sleep 3 - not necessary, install global libs below instead, it takes time too
#  - yarn global add mocha@3.2.0
#  - yarn global add istanbul@0.4.5
#  - mysql -u root -e "CREATE DATABASE spark /*\!40100 COLLATE 'utf8_general_ci' */;"
#  - mysql -u root spark < lib/db/mysql/spark_cache.sql
#  - /bin/bash dev.sh start

script:
  - php -v
  - node -v
  - pwd
  - node node_modules/protractor/bin/protractor conf.js

#after_success:
#  - cat ./coverage/lcov.info | node node_modules/coveralls/bin/coveralls.js || cat ./coverage/lcov.info | node node_modules/coveralls/bin/coveralls.js || cat ./coverage/lcov.info | node node_modules/coveralls/bin/coveralls.js

